[Add]ユーザー新規作成のシステムスペック
ryota1116/sample_app_for_rspec pull request #5
Opened 2020-05-05 07:22 UTC by ryota1116

### 実装内容
- Gem'capybara'と'webdrivers'のインストール
- ユーザー新規作成のシステムスペック

### テスト成功のキャプチャ
<img width="959" alt="スクリーンショット 2020-05-05 16 18 12" src="https://user-images.githubusercontent.com/60560627/81042858-06755400-8eec-11ea-8dfe-772f53aa9f7d.png">

2020-05-05 10:02 UTC, ryota1116 commented
## ログイン、ログアウト機能のシステムスペック
### テスト成功のキャプチャ
<img width="1041" alt="スクリーンショット 2020-05-05 19 00 47" src="https://user-images.githubusercontent.com/60560627/81054972-bce43380-8f02-11ea-9b8f-f15c20d08b5f.png">

2020-05-05 17:25 UTC, yuji91 requested changes

2020-05-05 17:25 UTC, yuji91 commented on spec/rails_helper.rb
> +  # config.include Sorcery::TestHelpers::Rails::System
何か対応予定であれば、TODOを残した方が分かりやすいですね。
```suggestion
  # TODO: xxの理由でxxできない
  # config.include Sorcery::TestHelpers::Rails::System
```

2020-05-05 17:28 UTC, yuji91 commented
> login_user.password

パスワード部分はFactoryで定義しているものをベタ打ちする形で大丈夫です！
RSpecではDRYにし過ぎず、都度直打ちして記載することがあります。

また、SorceryのRSpec用のヘルパーメソッドを使うのは難易度が高いので対応しなくて大丈夫です！

2020-05-06 09:20 UTC, ryota1116 commented
### ユーザー編集機能のシステムスペック

- ユーザー編集のシステムスペックを作成
- マクロ(ヘルパーメソッド)を作成
  - `spec/support/login_macros.rb`にlogin(user)メソッドを定義。

2020-05-06 16:44 UTC, ryota1116 commented on spec/system/tasks_spec.rb
> +    end
84~90行目と重複しているため、削除予定。

2020-05-06 16:53 UTC, ryota1116 commented
#### タスクの新規作成、編集、削除のシステムスペック作成
タスクは必ずユーザーと関連付けた上で作成するものだと思い、勝手にTaskモデルに`belongs_to :User`を追記した上でテストを記述したのですが、その必要はなかったでしょうか？

2020-05-06 16:55 UTC, ryota1116 commented
##### 追加予定
- 「マイページにユーザーが新規作成したタスクが表示されること」というテスト
- spec実行時にブラウザの表示有無を切り替える設定
- 実行されるテストケースを限定できる設定

2020-05-07 02:22 UTC, yuji91 approved these changes
細かいフォーマット以外は問題ないと思います！

2020-05-07 02:22 UTC, yuji91 commented on app/views/tasks/index.html.erb
> +      <% end %>
```suggestion
      <% if current_user&.my_object?(task) %>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      <% end %>
```

2020-05-07 02:22 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +    end
```suggestion
    before { login(user) }
```

2020-05-07 02:22 UTC, yuji91 commented on spec/system/user_sessions_spec.rb
> +
改行する部分が統一されていないのが気になります。個人的には改行はしなくても良いかと思っています。

2020-05-07 02:24 UTC, yuji91 commented
`belongs_to :user`は勝手に追加してOKです！

2020-05-07 02:39 UTC, ryota1116 commented on spec/system/user_sessions_spec.rb
> +
この指摘頂いている箇所は、空行のことでしょうか？

2020-05-07 02:43 UTC, ryota1116 commented
### システムスペック成功のキャプチャ

<img width="810" alt="スクリーンショット 2020-05-07 11 42 52" src="https://user-images.githubusercontent.com/60560627/81248688-e498e000-9057-11ea-8237-9d2200cb4c20.png">

2020-05-07 03:16 UTC, ryota1116 commented on app/views/tasks/index.html.erb
> +      <% end %>
bf76c02 で修正しました！

2020-05-07 03:16 UTC, ryota1116 commented on spec/system/tasks_spec.rb
> +    end
bf76c02 で修正しました。

2020-05-07 03:17 UTC, ryota1116 commented on spec/system/tasks_spec.rb
> +    end
f10e5ad で削除済。

2020-05-07 03:18 UTC, ryota1116 commented on spec/rails_helper.rb
> +  # config.include Sorcery::TestHelpers::Rails::System
こちら 9ddc5bd で削除しました。

2020-05-07 03:20 UTC, ryota1116 commented
https://github.com/ryota1116/sample_app_for_rspec/pull/5#issuecomment-624766737 は f10e5ad で対応しました。

2020-05-07 03:30 UTC, ryota1116 commented on spec/system/user_sessions_spec.rb
> +
0e60323 で修正しました。

2020-05-07 03:36 UTC, yuji91 approved these changes

2020-05-07 03:36 UTC, yuji91 approved these changes
- [x] 「マイページにユーザーが新規作成したタスクが表示されること」というテスト
- [x] spec実行時にブラウザの表示有無を切り替える設定
- [x] 実行されるテストケースを限定できる設定

2020-05-07 08:03 UTC, merged